### ISSUE TITLE
Make Deployment Type field required

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#466] opened 2019-09-06 14:58 UTC
Deployment Type field should be required for sensor deployments of types: Pressure Transducer, Meteorological Station, and Thermometer; but not for other sensor types.

**Comment by HansVraga** [comment] 2019-09-06 14:58
@lprivette is it possible to make it required for some but not others?

**Comment by lprivette** [comment] 2019-09-06 15:06
Probably --I haven't done this with angularJS yet, but I'd be surprised if we couldn't do this. I'd have to look into it (also I am out of hours). What is the priority on this?

**Comment by lprivette** [comment] 2019-09-06 15:34
To clarify this would just be requiring it on the client-side. If some one wanted to submit it via a rest client there would be no requirement.

**Comment by lprivette** [comment] 2020-06-05 19:36
duplicate of https://github.com/USGS-WiM/STNWeb/issues/492

**Closed as completed by lprivette** 2020-06-05 19:36 UTC
